name: Deploy to K8s

on:
  push:
    branches:
      - main


jobs:
  setup-gcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
     

      - name: Create GKE Cluster
        run: |
          gcloud container clusters create my-cluster \
            --num-nodes=2 \
            --machine-type=n1-standard-2 \
            --zone=europe-west1-b

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install kubectl

            

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-cluster --region europe-west1-b
          kubectl config set-context my-context --cluster=my-cluster
          kubectl config use-context my-context
          gcloud config set project zinc-strategy-393412
          kubectl apply -f deployment.yaml
